import Bootstrap from "@/components/Bootstrap";
import NavBar from "@/components/NavBar";
import "bootstrap/dist/css/bootstrap.css";

export const metadata = {
  title: "Imagenes mysql",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-bs-theme="dark">
      <body>
        <Bootstrap />
        <NavBar />
        {children}
      </body>
    </html>
  );
}
